version: '3'

services:
  
  firefox:
    image: selenium/standalone-firefox:4.15.0-20231129
    shm_size: '2gb'
    ports:
      - 4444:4444 # Selenium service
      - 5900:5900 # VNC server
      - 7900:7900 # VNC browser client
    environment:
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=15
      - SE_NODE_SESSION_TIMEOUT=30
  
  chrome:
    image: selenium/standalone-chrome:4.15.0-20231129
    shm_size: '2gb'
    ports:
      - 4441:4444 # Selenium service
      - 5901:5900 # VNC server
      - 7901:7900 # VNC browser client
    environment:
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=15
      - SE_NODE_SESSION_TIMEOUT=30
  
  edge:
    image: selenium/standalone-edge:4.15.0-20231129
    shm_size: '2gb'
    ports:
      - 4442:4444 # Selenium service
      - 5902:5900 # VNC server
      - 7902:7900 # VNC browser client
    environment:
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=15
      - SE_NODE_SESSION_TIMEOUT=30

  python:
    image: python:3.11.7-alpine3.18
    volumes:
      - ./../:/test
    working_dir: /test
    command: sh -c "pip install -r requirements-lock.txt && sh"
    tty: true