name: Run Tests (parallel)

on: 
    workflow_dispatch:
    pull_request:
        types:
            - opened
            - edited
        branches:
            - main
            - 'releases/**'

jobs:
    test:
        name: Run tests
        runs-on: ubuntu-latest
        container: node:20-bookworm

        strategy:
            fail-fast: false
            matrix:
                browser: ['firefox', 'chrome', 'edge']

        services:
            selenium:
                image: selenium/standalone-${{ matrix.browser }}:4.15.0-20231129
                options: --shm-size 2gb
                ports:
                    - 4444:4444
                env:
                    SE_NODE_OVERRIDE_MAX_SESSIONS: true
                    SE_NODE_MAX_SESSIONS: 15
                    SE_NODE_SESSION_TIMEOUT: 30
        
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: '3.11'
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                python -m pip install -r requirements-lock.txt
            
            - name: Test with pytest
              run: pytest -vv --use-browser remote
              env:
                SELENIUM_BROWSER: ${{ matrix.browser }}