name: Run Tests (parallel)

on: [workflow_dispatch]

jobs:
    test:
        name: Run tests
        runs-on: ubuntu-latest

        container:
            image: python:3.11.7-alpine3.18

        strategy:
            fail-fast: false
            matrix:
                browser: ['firefox', 'chrome', 'edge']

        services:
            selenium:
                image: selenium/standalone-${{ matrix.browser }}:4.15.0-20231129
                options: --shm-size=2gb
                env:
                    SE_NODE_OVERRIDE_MAX_SESSIONS: true
                    SE_NODE_MAX_SESSIONS: 15
                    SE_NODE_SESSION_TIMEOUT: 30
        
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v4
              with:
                python-version: "3.11.7"
            - run: pip install -r requirements-lock.txt
            - run: pytest -vv --use-browser remote
              env:
                SELENIUM_HOST: ${{ matrix.browser }}
